#
# Inspired by https://github.com/dictyBase/dicty-components-login/blob/161e12ff35b27f9b1c81c0deefa7417f56ce10c5/.github/workflows/automerge-dependabot.yml
#

name: dependabot[bot]
on: [pull_request]
jobs:
  Automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Wait for other checks
        uses: lewagon/wait-on-check-action@v0.1
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: merge
        uses: ridedott/merge-me-action@v1.8.61
        with:
          GITHUB_LOGIN: dependabot[bot]
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          MERGE_METHOD: "squash"
          PRESET: DEPENDABOT_PATCH
